### ISSUE TITLE
id of built-in themes had been changed on nightly

### ISSUE THREAD

**Issue by tiansh** [Claymont/theme-scheduler#1]
```diff
- firefox-compact-dark@mozilla.org@personas.mozilla.org
+ firefox-compact-dark@mozilla.org
- firefox-compact-light@mozilla.org@personas.mozilla.org
+ firefox-compact-light@mozilla.org
```

This currently only apply on Nightly version. Stable and beta version not effected.

**Comment by Claymont** [comment]
Thank you for informing me of the change.

Not much breakage, only problem I see is that the drop-downs in the option page does not select the correct theme on a new install (because the extension adds the incorrect ID's if Local Storage is empty). It will still change to the right theme even though the ID's are incorrect.

Pressing the save button once makes the problem go away as that part of the extension queries the browser for the correct ID's.

I find this bug to be small enough that I won't fix it until v63 hits the Release channel. I'll keep this issue Open in hopes that I remember doing so.

Thanks again.

**Comment by Claymont** [comment]
ID's have now been changed in the extension, so marking this as closed.
